### ISSUE TITLE
Logarithmusfunktionen sind fehlerhaft

### ISSUE THREAD

**Issue by falcopr** [MichaeIDietrich/Numerik-Project#10]
Bitte das log10 richtig implementieren. Schaut euch dazu die Tests an in der Klasse
Außerdem muss die Implementierung nach den 6 Tests in der Klasse MathLib_TestFixture im Package numeric_calc_test erfolgen. Schaut demnach nach den "Assertions" --> Ergebnisannahmen.

Die Logarithmusfunktion gibt folgenden fehler: 

java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.
    at java.math.BigDecimal.divide(Unknown Source)
    at numerik.calc.MathLib.log10(MathLib.java:144)
    at numerik.calc_test.MathLib_TestFixture.log10__Logarithmus_Base_10_Test_One(MathLib_TestFixture.java:109)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

Revision: f64af6d92277203580487cd8384115fe1b6db3ac
Author: falcoprescher
Date: 26.04.2012 15:08:02
Message:
Einbauen von log10_Tests

---

Modified : Numerik Project/src/numerik/calc_test/MathLib_TestFixture.java

**Comment by falcopr** [comment]
Für den log10 einer Zahl mit hohen Exponenten, wird der Logarithmus falsch berechnet. Bitte beheben!
(siehe Tests, die fehlschlagen)

Revision: 60d402282fde46c94557a33cd28becd8d1389505
Author: falcoprescher
Date: 27.04.2012 08:59:36
Message:
Bereinigung von log10 Tests

## Löschen des Importes der BigDecimal-Library, da diese fehlerhaft eingebunden wurde

Modified : Numerik Project/src/numerik/calc/MathLib.java
Modified : Numerik Project/src/numerik/calc_test/MathLib_TestFixture.java

**Comment by MichaeIDietrich** [comment]
ich bin dafür, dass wir auf Logarithmus, etc. verzichten, weil der Aufwand der Berechnung des Logarithmus logarithmisch ;) steigt und wir den Logarithmus auch momentan nicht mehr brauchen

**Comment by falcopr** [comment]
Ich bin deiner Meinung Milchaelus. Logarithmus brauchen wir nicht.
